{
  "description": "Experience luxury at this amazing apartment...",
  "host_name": "Ahmed",
  "host_picture": "https://...",
  "host_about": "I love hosting and welcoming guests...",
  "host_is_superhost": true,
  "host_total_listings": 17,
  "house_rules": "No smoking. No parties. Quiet hours after 10pm...",
  "amenities": [
     "Pool",
     "Kitchen",
     "Dedicated workspace",
     "Gym",
     "Free parking on premises"
  ],
  "address": "Downtown Dubai, Dubai, UAE",
  "lat": 25.1934,
  "lng": 55.2654,
  "photos": [...long list...],
  "space": "The apartment offers a fully equipped kitchen...",
  "guest_access": "You will have access to the entire apartment...",
  "interaction_with_guests": "Available via phone and WhatsApp",
  "neighborhood_overview": "Located next to Dubai Mall and Burj Khalifa...",
  "transit": "Metro station within a 7-minute walk...",
  "property_type": "Entire rental unit",
  "bedrooms": 2,
  "beds": 5,
  "bathrooms": 2,
  "accommodates": 6
}
